name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: welcome message
          run: echo "My firstgithub action"

        - name: list files
          run: ls

        - name: Read file
          run: car README.md

         


